"""A

Revision ID: 5db363f3e7ed
Revises: f1f24e2b8f76
Create Date: 2023-02-22 00:44:16.883796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db363f3e7ed'
down_revision = 'f1f24e2b8f76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
